BEGIN;
UPDATE productores SET proyecto = 'Sin Proyecto';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Maria de Lourdes Mensa Cerquera', vereda = 'El Jigual 2', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '34554040';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Atanasio Garcia Perez', vereda = 'El Jigual 2', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '10544540';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Guillermo Humberto Moncada Menza', vereda = 'El Jigual 2', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '76290507';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Alirio Sanchez Muñoz', vereda = 'El Jigual 2', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '10106323';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Carlos Adelmo Silva Atehortua', vereda = 'El Jigual 2', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '76320685';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Rosalba Andrea Astaiza Bolaños', vereda = 'El Jigual 2', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '34330581';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Irma Ines Astaiza', vereda = 'El Jigual 2', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '34523881';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Anuar Adrian Astaiza Muñoz', vereda = 'El Jigual 2', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '1060238864';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Gabi Stella Collazos Astaiza', vereda = 'El Jigual 2', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '25627858';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Jose Andres Narvaez Guañarita', vereda = 'El Jigual 2', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '10575136';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Sandra Patricia Astaiza Hernandez', vereda = 'El Jigual 2', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '25628735';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Armida Ordoñez Narváez', vereda = 'El Jigual 2', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '25627862';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Yeim Sofia Vargas Gutierres', vereda = 'El Jigual 2', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '25628171';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Carmen Delia Coque Urrea', vereda = 'El Jigual 2', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '25628696';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Felipe Muñoz Astaiza', vereda = 'El Jigual 2', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '76306436';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Duban Ernesto Collazos', vereda = 'El Jigual 2', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '1061716801';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Ismael Antonio Cuaji', vereda = 'El Jigual 2', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '10575065';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Miller Fernando Muñoz Pardo', vereda = 'Mirador', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '1002876437';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Elias Bolaños Mosquera', vereda = 'Mirador', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '10291996';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Ruben Dario Chilito Astaiza', vereda = 'Mirador', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '76314811';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Yudy Paola Coque Astaiza', vereda = 'Mirador', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '25628454';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Wildeman Mauricio Coque Chilito', vereda = 'Mirador', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '1061707699';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Alexander Tintinago Fernández', vereda = 'Mirador', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '1061735931';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Carlos Albeiro Orozco Bahos', vereda = 'Mirador', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '76276263';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Marisol Coque Hoyos', vereda = 'Mirador', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '1060237379';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Luis Carlos Astaiza', vereda = 'Mirador', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '10575078';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Luz Eddy Mosquera Diaz', vereda = 'Mirador', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '34536875';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Jaime Humberto Hoyos Ocoro', vereda = 'Mirador', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '76290446';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Alirio Tombe Hoyos', vereda = 'Mirador', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '76317893';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Oscar Armando Quilindo Camayo', vereda = 'Mirador', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '4788051';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Yina Cecilia Pillimur Benavides', vereda = 'Mirador', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '34324603';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Suli del Carmen Ruiz', vereda = 'Mirador', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '34536354';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Maria Cristina Astaiza Hernández', vereda = 'Mirador', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '25628736';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Jadyr Astaiza Coque', vereda = 'Mirador', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '1060236659';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Ximena Sotelo', vereda = 'Piedra de león', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '34557594';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Ever Omar Zambrano Muñoz', vereda = 'Piedra de león', municipio = 'Sotará' WHERE REPLACE(cedula, '.', '') = '10575132';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Hector Willard Chalapu Muñoz', vereda = 'Piedra de león', municipio = 'Sotará' WHERE REPLACE(cedula, '.', '') = '10575125';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Ramiro Castillo Mosca', vereda = 'Piedra de león', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '76327892';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Jose Gerardo Anacona Yace', vereda = 'Piedra de león', municipio = 'Sotará' WHERE REPLACE(cedula, '.', '') = '10575117';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Sandra Lorena Chalapu Muñoz', vereda = 'Piedra de león', municipio = 'Sotará' WHERE REPLACE(cedula, '.', '') = '25628222';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Maria Carlina Chilito Astaiza', vereda = 'Piedra de león', municipio = 'Sotará' WHERE REPLACE(cedula, '.', '') = '34543804';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Ana Ruth Avirama Meneses', vereda = 'Piedra de león', municipio = 'Sotará' WHERE REPLACE(cedula, '.', '') = '1060236279';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Mariela Coque', vereda = 'Piedra de león', municipio = 'Sotará' WHERE REPLACE(cedula, '.', '') = '25628392';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Maicol Eduart Mueses Yace', vereda = 'Piedra de león', municipio = 'Sotará' WHERE REPLACE(cedula, '.', '') = '1061763987';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Eider Arnulfo Zambrano Chilito', vereda = 'Piedra de león', municipio = 'Sotará' WHERE REPLACE(cedula, '.', '') = '76327826';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Alfonso Ordoñez Salazar', vereda = 'Piedra de león', municipio = 'Sotará' WHERE REPLACE(cedula, '.', '') = '76321243';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Jorge Enrique Charo Peteche', vereda = 'Josefina', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '76328222';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Nery Viviana Sanchez Coaji', vereda = 'Josefina', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '1061730721';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Paola Andrea Sánchez Serna', vereda = 'Josefina', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '1061703828';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Jose Roberto Gutierrez Sanchez', vereda = 'Josefina', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '10538012';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Duber Alveiro Vasquez Chilito', vereda = 'Josefina', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '1060238812';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Laurentino Sanchez Sanchez', vereda = 'Josefina', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '10575063';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Gloria Stella Bolaños Yace', vereda = 'Josefina', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '34563358';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Yeni Amparo Bolaños Muñoz', vereda = 'Josefina', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '25628034';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Marino Narvaez Muñoz', vereda = 'Josefina', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '10541232';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Alba Ceneida Fernández Solarte', vereda = 'Josefina', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '25682684';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Jose Gerardo Levaza Gurrute', vereda = 'Josefina', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '76290101';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Blanca Nelli Ydrobo Santiago', vereda = 'Josefina', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '25276463';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Jose Guillermo Chapues Caso', vereda = 'Josefina', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '76325946';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Carlos Alberto Narvaez Muñoz', vereda = 'Josefina', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '10535219';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Lucio Mapallo Melenge', vereda = 'Josefina', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '10575121';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Jose Miguel Termal Malte', vereda = 'Josefina', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '5253954';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Marco Aurelio Granados Herrera', vereda = 'Josefina', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '10532555';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Blanca Magnolia Hormiga Chapues', vereda = 'Josefina', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '1002876646';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Ruben Dario Basto', vereda = 'Josefina', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '76290044';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Juan Pablo Termal Tutalcha', vereda = 'Josefina', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '1060238630';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Magliony Narvaez Muñoz', vereda = 'Josefina', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '76303647';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Dany Bibiana Hormiga Chapues', vereda = 'Josefina', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '1060239261';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Sixta Tulia Chapues Caso', vereda = 'Josefina', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '34330598';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Jesus Alfonso Chapues Caso', vereda = 'Josefina', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '10297398';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Ramiro Narvaez Mapallo', vereda = 'Josefina', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '76290307';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Eyver Alfredo Melenje', vereda = 'Josefina', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '76290538';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Ferney Alexander Yalanda Pausa', vereda = 'Rio Negro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '1060237679';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Jander Andres Perdomo Yace', vereda = 'Rio Negro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '10290482';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Lorenzo Tombe Yace', vereda = 'Rio Negro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '10290328';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Ana Teresa Camayo Chaparral', vereda = 'Rio Negro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '25628686';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Yaned Patricia Camayo', vereda = 'Rio Negro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '25284669';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Edwin Ivan Idrobo Santiago', vereda = 'Rio Negro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '1061723670';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Melba Magnolia Avirama Olave', vereda = 'Rio Negro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '1060237237';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Jesús María Tombe Yace', vereda = 'Rio Negro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '10575100';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Maria Cruz Sánchez de Conejo', vereda = 'Rio Negro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '34532677';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Marino Tombe Yace', vereda = 'Rio Negro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '10575092';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Wilfredo Guauña Niquinas', vereda = 'Rio Negro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '4611925';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Benjamin Meneses Paredes', vereda = 'Rio Negro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '76310062';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Maria Delia Magon Gurrute', vereda = 'Rio Negro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '25628727';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Dinael Francisco Velasco Camayo', vereda = 'Rio Negro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '1061724409';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Ana Cleotilde Camayo Yalanda', vereda = 'Rio Negro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '25628220';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Jose Rafael Gutierrez Sanchez', vereda = 'Rio Negro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '10575058';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Maria Cecilia Tombe Yace', vereda = 'Rio Negro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '25628702';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Angye Viviana Alonso Chaparral', vereda = 'Rio Negro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '1061803252';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Mariana Velasco Guauña', vereda = 'Rio Negro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '1061711097';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Mariela Guauña Cuchumbe', vereda = 'Rio Negro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '34550377';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Miriam Patricia Hidrobo Perdomo', vereda = 'Rio Negro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '25628152';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Jorge Apolinar Mensa Cerquera', vereda = 'El Jigual 2', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '76290325';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Yoher Alexis Quelal Coaji', vereda = 'El Jigual 2', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '1060238172';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Carmen Nery Velasco Almendra', vereda = 'Rio Negro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '1064427718';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Ismenia Coaji Guadir', vereda = 'Rio Negro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '25290321';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Milton Dario Cerquera Urrutia', vereda = 'Rio Negro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '76290304';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Luis Humberto Morales Perafan', vereda = 'Centro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '76290488';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Omar Adriano Coque', vereda = 'Centro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '76290685';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Maria Rubiela Magon Niquinaz', vereda = 'Centro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '25628709';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Maria Isabel Yalanda Pausa', vereda = 'Centro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '25628072';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Sandra Mileth Susatama Astaiza', vereda = 'Deposito', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '1060238794';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Nilson Jair Muñoz Muñoz', vereda = 'Deposito', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '1060236089';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Esperanza Rivera Garzón', vereda = 'Deposito', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '25628666';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Jeison Almir Yacumal Coque', vereda = 'Deposito', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '1061709854';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Jose Rey Cuaji Susatama', vereda = 'Deposito', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '10575076';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Juan Bautista Coque Rivera', vereda = 'Deposito', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '4749246';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Francisco Arnol Chalapu Muñoz', vereda = 'Deposito', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '1430695';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Hector Ignacio Narvaez Bolaños', vereda = 'Deposito', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '1061758574';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Anderson Muñoz Olave', vereda = 'Deposito', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '1060236288';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Arnulfo Muñoz', vereda = 'Deposito', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '10535942';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Rodrigo Golondrino Melenje', vereda = 'Deposito', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '76322728';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Nestor Fabian Conejo Perdomo', vereda = 'Deposito', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '1061744523';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Maria Doris Perdomo Coque', vereda = 'Deposito', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '34528698';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Juan Camilo Velasco Sandoval', vereda = 'Deposito', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '1002961956';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Pedro Anibal Coaji Susatama', vereda = 'Deposito', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '10526417';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Macister Muñoz Alonso', vereda = 'Deposito', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '10575126';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Jabier Magon Gurrute', vereda = 'Deposito', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '76307746';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Fabio Nelson Termal Basto', vereda = 'Deposito', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '83042886';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Edelmira Quilindo Astaiza', vereda = 'Deposito', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '25628664';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Guido Hernan Meneses', vereda = 'Deposito', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '10545716';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Olga Fani Velazco Salazar', vereda = 'Rio Claro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '25706853';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Carmelina Muñoz de Mosca', vereda = 'Rio Claro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '25628657';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Miriam Ester Magin Olave', vereda = 'Rio Claro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '25628649';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Fernando Arturo Olave Mosquera', vereda = 'Rio Claro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '76307245';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Maria Esther Gutierrez de Callapu', vereda = 'Rio Claro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '25628600';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Pedro Leon Perdomo Gutierrez', vereda = 'Rio Claro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '10530463';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Aura Elisa Olave Mosquera', vereda = 'Rio Claro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '52222636';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Maria Claudia Muñoz Olave', vereda = 'Rio Claro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '1060237167';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Jose Cipriano Avirama', vereda = 'Rio Claro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '4749488';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Aura Matilde Muñoz Alonso', vereda = 'Rio Claro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '25628734';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Rosa Elena Yule Guasaquillo', vereda = 'Rio Claro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '34599376';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Gerardina Gurrute', vereda = 'Rio Claro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '25628697';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Helber Olmedo Camayo', vereda = 'Rio Claro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '4611633';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Jose Glenis Serna Bolaños', vereda = 'Rio Claro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '76313627';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Luz Marina Quintero Muñoz', vereda = 'Rio Claro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '35511195';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Rut Deomira Olave Mosquera', vereda = 'Rio Claro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '25628714';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Luz Mila Cuaji Perdomo', vereda = 'Rio Claro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '25628731';
UPDATE productores SET proyecto = 'Proyecto Paletará', nombre_completo = 'Aida Ligia Olave Mosquera', vereda = 'Rio Claro', municipio = 'Puracé' WHERE REPLACE(cedula, '.', '') = '34562649';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '4771236';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '39623902';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '25693683';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '29774725';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '1005979002';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '106476394';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '25693546';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '31476021';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '25694102';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '1063810090';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '4771164';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '25702819';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '25691306';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '13039313';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '25694177';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '1061770754';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '25693801';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '34547634';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '4788173';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '4771252';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '10291060';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '1806967';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '4774379';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '10455131';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '4771199';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '4771279';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '16783793';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '52158097';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '34329981';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '25693804';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '25694101';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '87217881';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '11389333';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '76290011';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '25693701';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '34485089';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '4787769';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '10545079';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '98341686';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '55163823';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '30688542';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '34550554';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '10290755';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '76309539';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '76316673';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '4771314';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '76295922';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '76290042';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '25697112';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '1064676830';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '1061698446';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '4771241';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '98341876';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '1002821603';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '4771399';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '10308477';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '1063817889';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '1060237416';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '34315870';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '76330564';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '34562182';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '4749497';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '76317110';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '36381597';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '1061704137';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '34323133';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '39793246';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '48600036';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '25700280';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '34321845';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '34543947';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '16667705';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '4773045';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '1064676497';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '1061791193';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '1064677022';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '1081702462';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '1517795';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '4773064';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '4771288';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '1061794141';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '1063809524';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '1063806941';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '4773002';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '76308041';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '4771230';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '25290509';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '10532886';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '1061693094';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '26308173';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '1517686';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '4771187';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '10516112';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '76314835';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '1061713441';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '1061706732';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '1061686462';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '48661807';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '25693748';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '1061733459';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '4771096';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '76028835';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '25706328';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '4771606';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '1064676728';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '34475112';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '25693772';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '1064676399';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '76030030';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '25693713';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '4771438';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '76296906';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '1064676920';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '1064676291';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '1060238959';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '1064677004';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '1061746316';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '76290202';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '51786901';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '10542047';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '48661808';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '98396591';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '10548542';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '1517789';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '76312936';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '351677';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '76284900';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '76306996';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '1064676922';
UPDATE productores SET proyecto = 'Proyecto Sotará' WHERE REPLACE(cedula, '.', '') = '76310162';
COMMIT;